[package]
name = "crossyword"
license = "GPL-3.0-only"
version = "0.1.1"
edition = "2021"
description = "An awesome crossword puzzle generator"
readme = "README.md"
repository = "https://github.com/lukasvrenner/crossyword"
categories = ["crossword", "GUI"]
keywords = ["crossword"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
